### ISSUE TITLE
Throw error on imac

### ISSUE THREAD

**Issue by russweir** [Peripona/bulk-clean-repos#2]
hey mate,
   i am having issues running the script, i get the following error?
$ node fetchSaveRepo.js
module.js:550
    throw err;
    ^
Error: Cannot find module 'node-fetch'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/russellweir/Desktop/repos/bulk-clean-repos/fetchSaveRepo.js:1:77)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by robertgrzonka** [comment]
The reason of this prompt is that `fetchSaveRepo.js` file requires `node-fetch` module. This is nature of Node.js. Suggested option is to initialize new project in your `$PATH` where you have clone of this repo (this should be `Users/rusellweir/Desktop/repos/bulk-clean-repos`). 

You can do it like so:

```shell
npm init #you can just simply constantly click Return↩︎ on your Mac
npm install node-fetch 
```

or you can use [Yarn](https://yarnpkg.com) like me:

```shell
yarn init
yarn add node-fetch
```

After that it should be ready to go.
